const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const API_BASE_URL=String(window.__APP_CONFIG__?.API_BASE_URL||'').replace(/\/$/,'');
const traits={
  extraversion:{name:'外向性',guide:'連結推動者',tagline:'在連結與獨處之間找到能量節奏',color:'#E99A45',image:'./characters/extraversion.png'},
  conscientiousness:{name:'盡責性',guide:'秩序建設者',tagline:'讓重要的事從想法走向完成',color:'#3B6FCB',image:'./characters/conscientiousness.png'},
  openness:{name:'開放性',guide:'世界探索者',tagline:'為觀念、審美與可能性保留空間',color:'#7667E8',image:'./characters/openness.png'},
  agreeableness:{name:'宜人性',guide:'關係協調者',tagline:'理解他人，也守住彼此的邊界',color:'#45A58A',image:'./characters/agreeableness.png'},
  emotionalSensitivity:{name:'情緒敏感性',guide:'內在感知者',tagline:'辨認壓力、風險與恢復的訊號',color:'#D96C7D',image:'./characters/emotional-sensitivity.png'}
};
let turn=0,slotRemaining=0;
const toast=m=>{const x=$('#toast');x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)};
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function api(url,options={}){const accessCode=sessionStorage.getItem('bigfive_access_code')||'';const attempts=url==='/api/interview'?2:1;for(let attempt=0;attempt<attempts;attempt++){try{const r=await fetch(`${API_BASE_URL}${url}`,{...options,credentials:'include',headers:{'content-type':'application/json',...(accessCode?{'x-access-code':accessCode}:{}),...(options.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok){if(attempt+1<attempts&&(r.status===429||r.status>=500)){await pause(1200);continue}const error=new Error(d.error||'服務暫時無法回應');error.status=r.status;throw error}return d}catch(error){if(attempt+1<attempts&&!error.status){await pause(1200);continue}throw error}}}
function show(id){['gate','codeReveal','interview','report'].forEach(x=>$(`#${x}`).classList.toggle('hidden',x!==id));$('.group-intro').classList.toggle('hidden',id!=='gate')}
function updateClaimButton(){$('#claim').disabled=slotRemaining===0||!$('#serviceConsent').checked}
function syncConsent(consent={}){$('#dataSettings').classList.remove('hidden');$('#manageResearchConsent').checked=Boolean(consent.research);$('#consentStatus').textContent=consent.research?'目前已同意用於產品改進；你可以取消勾選並保存以撤回。':'目前僅用於完成訪談與保存報告，不會在產品改進後台展示原始回答。'}
async function refreshSlots(){try{const a=await api('/api/access/availability');slotRemaining=a.remaining;$('#slots').textContent=`今日剩餘 ${a.remaining} / ${a.limit} 個名額`;updateClaimButton()}catch{$('#slots').textContent='名額讀取失敗'}}
function coverage(v={}){$('#dims').innerHTML=Object.entries(traits).map(([k,t])=>`<div class="dim"><label><span>${t.name}</span><span>${Math.round(v[k]||0)}%</span></label><div class="bar"><i style="width:${v[k]||0}%;background:${t.color}"></i></div></div>`).join('')}
async function next(answer=''){const send=$('#send');let succeeded=false;try{send.disabled=true;send.textContent=answer?'正在分析…':'正在連接…';const d=await api('/api/interview',{method:'POST',body:JSON.stringify({answer})});succeeded=true;if(d.type==='report')return renderReport(d.report);turn++;$('#turn').textContent=turn;$('#question').textContent=d.question;$('#observation').textContent=d.observation;$('#answer').value='';coverage(d.coverageStatus||d.dimensionStatus)}catch(e){$('#observation').textContent='剛才的連線沒有完成，你的訪問碼和已填回答都仍然保留。';$('#question').textContent='點擊「重新嘗試」即可繼續，不會重複計算題數。';toast(e.message)}finally{send.disabled=false;send.textContent=succeeded?'提交回答':'重新嘗試'}}
const chips=items=>(items||[]).map(x=>`<span>${esc(typeof x==='string'?x:x.name||x.level)}</span>`).join('');
function renderDimension(d,i){const t=traits[d.key]||{guide:d.name,tagline:'',color:'#607080',image:''};return `<article class="dimension-card" style="--dimension-color:${t.color}">
  <div class="dimension-character"><img src="${t.image}" alt="${esc(t.guide)}角色立繪"><span>0${i+1}</span></div>
  <div class="dimension-heading"><small>${esc(d.name)} · ${esc(d.level)}</small><h3>${esc(t.guide)}</h3><p>${esc(t.tagline)}</p><div class="range"><b>${esc(d.range||`${d.score??'—'}`)}</b><span>傾向區間 · 非百分位</span></div></div>
  <div class="dimension-body"><p class="dimension-intro">${esc(d.introduction)}</p><p>${esc(d.judgment)}</p>
    <div class="facet-grid">${(d.facets||[]).map(f=>`<div><b>${esc(f.name)}</b><em>${esc(f.level)}</em><p>${esc(f.explanation)}</p></div>`).join('')}</div>
    <h4>判斷依據</h4><div class="evidence-list">${(d.evidence||[]).map(e=>`<div><b>${esc(e.context)}</b><p>${esc(e.behavior)}</p><small>${esc(e.meaning)}${e.condition?` · 條件：${esc(e.condition)}`:''}</small></div>`).join('')||'<p>目前證據仍不足。</p>'}</div>
    ${(d.counterEvidence||[]).length?`<p class="counter"><b>反向證據／限制：</b>${esc(d.counterEvidence.join('；'))}</p>`:''}
    <div class="two-note"><p><b>可能發揮的功能</b>${esc(d.strengthExpression)}</p><p><b>需要留意的代價</b>${esc(d.watchout)}</p></div>
    <small class="confidence"><b>${esc(d.confidence)} / 100</b> 證據可信度</small>
  </div></article>`}
function insightCards(title,items,render){return `<section class="insight-section"><div class="section-title"><span></span><h2>${title}</h2></div><div class="insight-grid">${(items||[]).map(render).join('')||'<p>目前沒有足夠資訊。</p>'}</div></section>`}
function renderReport(r){show('report');const rank=x=>Number.isFinite(Number(x.score))?Number(x.score):parseInt(x.range||0);const sorted=[...(r.dimensions||[])].sort((a,b)=>rank(b)-rank(a));const p=r.persona||{};const experimentCode=sessionStorage.getItem('bigfive_access_code')||'';$('#reportExperimentCode').textContent=experimentCode?`實驗代碼 ${experimentCode}`:'';$('#personaTitle').textContent=p.title||'你的五維輪廓';$('#personaTagline').textContent=p.tagline||'五個維度，共同寫成一個人。';$('#personaIntro').textContent=p.introduction||r.summary;$('#personaCharacter').src=(traits[sorted[0]?.key]||traits.openness).image;$('#summary').textContent=r.summary;$('#dimensionCards').innerHTML=sorted.map(renderDimension).join('');
  const facetRanking=(r.facetRanking?.length?r.facetRanking:sorted.flatMap(d=>(d.facets||[]).map(f=>({...f,dimensionKey:d.key})))).filter(f=>f.name).sort((a,b)=>rank(b)-rank(a)).map((f,i)=>({...f,rank:i+1}));
  const facetRankSection=facetRanking.length?`<section class="facet-ranking-section"><div class="section-title"><span></span><div><small>由高至低 · 共 ${facetRanking.length} 項</small><h2>你的子特質排序</h2><p>同一角色與代表色，表示它們屬於同一個五維家族；數值只用於本次訪談內部比較。</p></div></div><div class="facet-ranking">${facetRanking.map(f=>{const t=traits[f.dimensionKey]||traits.openness;return `<article style="--facet-color:${t.color}"><span class="facet-rank">${String(f.rank).padStart(2,'0')}</span><img src="${t.image}" alt="${esc(t.guide)}角色"><div><small>${esc(t.name)} · ${esc(f.level)}</small><h3>${esc(f.name)}</h3><p>${esc(f.portrait||f.explanation)}</p></div><b>${esc(f.range||f.score||'—')}</b></article>`}).join('')}</div></section>`:`<section class="legacy-report-note"><span class="eyebrow">舊版報告說明</span><h2>這份早期資料不包含完整的 15 項子特質</h2><p>為了避免憑空補造判斷，這裡不顯示不完整的排序。重新完成一次新版訪談，即可獲得完整 15 項排序、個人畫像與成長方案。</p></section>`;
  const stable=insightCards('穩定模式',r.stablePatterns,x=>`<article><h3>${esc(x.pattern||x)}</h3><p>${esc(x.evidence)}</p><small>${esc(x.when)}</small></article>`);
  const contradictions=insightCards('表面矛盾',r.apparentContradictions,x=>`<article><h3>${esc(x.pattern)}</h3><p>${esc(x.explanation)}</p><small>切換條件：${esc(x.trigger)}</small></article>`);
  const strengths=insightCards('優勢與代價',r.strengths,x=>`<article><h3>${esc(x.strength||x)}</h3><p>${esc(x.bestContext)}</p><small>過度使用：${esc(x.cost)}</small></article>`);
  const blind=insightCards('潛在盲區',r.blindSpots,x=>`<article><h3>${esc(x.blindSpot||x)}</h3><p>預警：${esc(x.signal)}</p><small>可嘗試：${esc(x.suggestion)}</small></article>`);
  const growth=insightCards('把理解變成行動',r.growthPlan,x=>`<article class="growth-card"><h3>${esc(x.title)}</h3><p>${esc(x.why)}</p><dl><dt>最小行動</dt><dd>${esc(x.microAction)}</dd><dt>如果…那麼…</dt><dd>${esc(x.ifThen)}</dd><dt>每週復盤</dt><dd>${esc(x.weeklyReview)}</dd><dt>守住邊界</dt><dd>${esc(x.guardrail)}</dd></dl></article>`);
  const values=insightCards('回答中反覆出現的價值主題',r.valueThemes,x=>`<article><h3>${esc(x.value)}</h3><p>${esc(x.evidence)}</p><small>可能的張力：${esc(x.tension)}</small></article>`);
  const interpersonal=r.interpersonalStyle||{};
  const work=r.learningAndWorkStyle||{};const workSection=`<section class="insight-section"><div class="section-title"><span></span><div><h2>學習與工作方式</h2><p>把人格傾向翻譯成環境適配與可驗證的小實驗，而不是替你決定專業或職業。</p></div></div><div class="work-style"><article><h3>更容易進入狀態的條件</h3><div class="facet-row">${chips(work.bestConditions)}</div></article><article><h3>任務方式</h3><p>${esc(work.taskApproach)}</p></article><article><h3>協作與回饋</h3><p>${esc(work.collaboration)}</p></article><article><h3>容易卡住的地方</h3><div class="facet-row">${chips(work.frictionPoints)}</div></article><article class="work-experiments"><h3>可以試行一週的實驗</h3>${(work.experiments||[]).map((x,i)=>`<p><b>0${i+1}</b>${esc(x)}</p>`).join('')}</article></div><p class="work-boundary">${esc(work.boundary)}</p></section>`;
  const supportFeedback=`<section class="support-feedback"><div class="feedback-copy"><span class="eyebrow">問題反饋</span><h2>讓這場訪談繼續變得更好</h2><p>在訪談中遇到頁面、訪問碼、報告或其他技術問題，都可以直接聯絡作者。來信時可附上畫面截圖與實驗代碼，請不要附上不希望公開的私人回答。</p><div class="feedback-links"><a href="mailto:xuziananan@gmail.com"><small>電子郵箱</small><b>xuziananan@gmail.com</b></a><a href="https://github.com/flaaaaaking/fictional-octo-waddle" target="_blank" rel="noopener noreferrer"><small>專案與技術反饋</small><b>GitHub 專案首頁 ↗</b></a><a href="https://github.com/flaaaaaking" target="_blank" rel="noopener noreferrer"><small>作者平台主頁</small><b>flaaaaaking ↗</b></a></div></div></section>`;
  const evidence=(r.evidenceAppendix||[]).filter(x=>x.context&&x.behavior);const evidenceSection=evidence.length?`<section class="evidence-appendix"><div class="section-title"><span></span><div><small>可追溯的行為依據 · 共 ${evidence.length} 條</small><h2>證據索引</h2><p>這裡是用於判定的摘要，不是逐字引用；題號可以幫你回看結論來自哪一次回答。</p></div></div><div class="evidence-index">${evidence.map(x=>`<article><b>${esc(x.id)} · 第 ${esc(x.sourceTurn)} 題</b><small>${esc(x.dimensionName)} · ${esc(x.facetName)}</small><p>${esc(x.behavior)}</p><em>${esc(x.context)}${x.condition?` · 條件：${esc(x.condition)}`:''}</em></article>`).join('')}</div></section>`:'';
  const componentLabels={coverage:'子特質覆蓋',concreteBehavior:'具體行為',crossContext:'跨情境核對',traceability:'來源可追溯',conditionsAndExceptions:'條件與例外',contradictionResolution:'矛盾解釋度'};const confidenceBreakdown=r.confidence?.components?`<div class="confidence-breakdown">${Object.entries(componentLabels).map(([key,label])=>`<span><small>${label}</small><b>${esc(r.confidence.components[key])}</b></span>`).join('')}</div>`:'';
  $('#reportDetails').innerHTML=facetRankSection+stable+contradictions+`<section class="insight-section"><div class="section-title"><span></span><h2>人際互動風格</h2></div><div class="interpersonal"><p><b>能動性</b>${esc(interpersonal.agency)}</p><p><b>共同性</b>${esc(interpersonal.communion)}</p><p><b>二者如何互動</b>${esc(interpersonal.interaction)}</p></div></section>`+workSection+values+strengths+blind+growth+insightCards('較可能隨環境改變的部分',r.changeablePatterns,x=>`<article><p>${esc(x)}</p></article>`)+evidenceSection+`<section class="confidence-panel"><h2>這份報告有多可信？</h2><div><b>${esc(r.confidence?.score)} / 100</b><p><strong>${esc(r.confidence?.level)}可信度</strong><br>${esc(r.confidence?.basis)}</p></div>${confidenceBreakdown}<p class="confidence-note">這個數字衡量的是具體例子、跨情境核對、條件與反例是否充分；它不是人格強度，也不是對你是否誠實的評分。</p><p class="fine">${esc(r.disclaimer)}</p></section>`+supportFeedback}
function restore(d){if(d?.type==='report')return renderReport(d.report);if(!d)return next();$('#question').textContent=d.question;$('#observation').textContent=d.observation;coverage(d.coverageStatus||d.dimensionStatus)}
$('#serviceConsent').onchange=updateClaimButton;
$('#claim').onclick=async()=>{try{$('#claim').disabled=true;const d=await api('/api/access/claim',{method:'POST',body:JSON.stringify({serviceConsent:$('#serviceConsent').checked,researchConsent:$('#researchConsent').checked})});sessionStorage.setItem('bigfive_access_code',d.code);syncConsent(d.consent);$('#issuedCode').textContent=d.code;show('codeReveal');slotRemaining=d.remaining;$('#slots').textContent=`今日剩餘 ${d.remaining} / 10 個名額`}catch(e){toast(e.message);refreshSlots()}};
$('#enterInterview').onclick=()=>{show('interview');coverage();next()};
$('#login').onclick=async()=>{try{const code=$('#code').value.trim().toUpperCase();sessionStorage.setItem('bigfive_access_code',code);await api('/api/access/login',{method:'POST',body:JSON.stringify({code})});const s=await api('/api/session');syncConsent(s.consent);show('interview');turn=s.turns;$('#turn').textContent=turn;restore(s.current)}catch(e){sessionStorage.removeItem('bigfive_access_code');toast(e.message)}};
$('#dataSettings').onclick=()=>$('#dataDialog').showModal();
$('#closeDataSettings').onclick=()=>$('#dataDialog').close();
$('#saveConsent').onclick=async()=>{try{$('#saveConsent').disabled=true;const d=await api('/api/consent',{method:'POST',body:JSON.stringify({researchConsent:$('#manageResearchConsent').checked})});syncConsent(d.consent);$('#dataDialog').close();toast('資料設定已保存')}catch(e){toast(e.message)}finally{$('#saveConsent').disabled=false}};
$('#send').onclick=()=>next($('#answer').value);$('#answer').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')$('#send').click()});
(async()=>{const sharedCode=new URLSearchParams(location.search).get('code');if(sharedCode){sessionStorage.setItem('bigfive_access_code',sharedCode.toUpperCase());history.replaceState({},'',location.pathname)}refreshSlots();try{const s=await api('/api/session');syncConsent(s.consent);show('interview');turn=s.turns;$('#turn').textContent=turn;restore(s.current)}catch{show('gate')}})();
